apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-compute
  labels:
    app: cloud-compute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-compute
  template:
    metadata:
      labels:
        app: cloud-compute
    spec:
      containers:
        - name: cloud-compute
          image: linuzj/edge-offload:cloud-compute
          ports:
            - containerPort: 8080
          env:
            - name: INTERNAL_HOST
              value: "0.0.0.0"
            - name: EXPOSE_PORT
              value: "8080"
          resources:
            requests:
              memory: "2Gi"
              cpu: "700m"
            limits:
              memory: "2Gi"
              cpu: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-compute-service
  labels:
    app: cloud-compute
spec:
  selector:
    app: cloud-compute
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
