apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  labels:
    app: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: linuzj/edge-offload:simulator
          env:
            - name: EDGE_COMPUTE_HOST
              value: "edge-compute-service"
            - name: EDGE_COMPUTE_PORT
              value: "8081"
            - name: EDGE_COMPUTE_PORT
              value: "8081"
            - name: AUDIO_PATH
              value: "/app/audio"
          volumeMounts:
            - name: audio-volume
              mountPath: /app/audio
      volumes:
        - name: audio-volume
          hostPath:
            path: /audio
            type: Directory
