apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-compute
  labels:
    app: edge-compute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-compute
  template:
    metadata:
      labels:
        app: edge-compute
    spec:
      containers:
        - name: edge-compute
          image: linuzj/edge-offload:edge-compute
          ports:
            - containerPort: 8081
            - containerPort: 8000 # Prometheus metrics
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          env:
            - name: CLOUD_URL
              value: "https://edge-offload-cloud-384230659213.europe-north1.run.app"
---
apiVersion: v1
kind: Service
metadata:
  name: edge-compute-service
  labels:
    app: edge-compute
spec:
  selector:
    app: edge-compute
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: metrics
  type: ClusterIP
