apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-compute
  labels:
    app: edge-compute
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-compute
  template:
    metadata:
      labels:
        app: edge-compute
    spec:
      containers:
        - name: edge-compute
          image: linuzj/edge-offload:edge-compute
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: edge-compute-service
  labels:
    app: edge-compute
spec:
  selector:
    app: edge-compute
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
